<?php
	/**
	 *	@package Paygateway
	 */

	// Define valid country codes
	define("ALGERIA", "DZ");
	define("BENIN", "BJ");
	define("BOTSWANA", "BW");
	define("BURKINA_FASO", "BF");
	define("BURUNDI", "BI");
	define("CAMEROON", "CM");
	define("CAPE_VERDE", "CV");
	define("CENTRAL_AFRICAN_REPUBLIC", "CF");
    define("CHAD", "TD");
	define("COMOROS", "KM");
	define("CONGO", "CG");
	define("COTE_DIVOIRE", "CI");
	define("DJIBOUTI", "DJ");
	define("EGYPT", "EG");
	define("EQUATORIAL_GUINEA", "GQ");
	define("ERITREA", "ER");
	define("ETHIOPIA", "ET");
	define("GABON", "GA");
	define("GAMBIA", "GM");
	define("GHANA", "GA");
	define("GUINEA", "GN");
	define("GUINEA_BISSAU", "GW");
	define("KENYA", "KE");
	define("LESOTHO", "LS");
	define("LIBERIA", "LR");
	define("MADAGASCAR", "MG");
	define("MALAWI", "MW");
	define("MALI", "ML");
	define("MAURITANIA", "MR");
	define("MAYOTTE", "YT");
	define("MOROCCO", "MA");
	define("MOZAMBIQUE", "MZ");
	define("NAMIBIA", "NA");
	define("NIGER", "NE");
	define("NIGERIA", "NG");
	define("REUNION", "RE");
	define("SAO_TOME_AND_PRINCIPE", "ST");
	define("SENEGAL", "SN");
	define("SIERRA_LEONE", "SL");
	define("SOMALIA", "SO");
	define("SOUTH_AFRICA", "ZA");
	define("ST_HELENA", "SH");
	define("SUDAN", "SD");
	define("SWAZILAND", "SZ");
	define("TANZANIA", "TZ");
	define("TOGO", "TG");
	define("TUNISIA", "TN");
	define("UGANDA", "UG");
	define("WESTERN_SAHARA", "EH");
	define("ZAIRE", "ZR");
	define("ZAMBIA", "ZM");
	define("ZIMBABWE", "ZW");

	// Antartica
	define("ANTARCTICA", "AQ");

	// Asia
	define("AFGHANISTAN", "AF");
	define("BANGLADESH", "BD");
	define("BHUTAN", "BT");
	define("BRUNEI", "BN");
	define("CAMBODIA", "CM");
	define("CHINA", "CN");
	define("HONG_KONG", "HK");
	define("INDIA", "IN");
	define("INDONESIA", "ID");
	define("JAPAN", "JP");
	define("KAZAKHSTAN", "KZ");
	define("KYRGYZSTAN", "KG");
	define("LAOS", "LA");
	define("MACAU", "MO");
	define("MALAYSIA", "MY");
	define("MALDIVES", "MV");
	define("MONGOLIA", "MN");
	define("NEPAL", "NP");
	define("PAKISTAN", "PK");
	define("PHILIPPINES", "PH");
	define("REPUBLIC_OF_KOREA", "KR");
	define("RUSSIA", "RU");
	define("SEYCHELLES", "SC");
	define("SINGAPORE", "SG");
	define("SRI_LANKA", "LK");
	define("TAIWAN", "TW");
	define("TAJIKISTAN", "TJ");
	define("THAILAND", "TH");
	define("TURKMENISTAN", "TM");
	define("UZBEKISTAN", "UZ");
	define("VIETNAM", "VN");

	// Australia
	define("AMERICAN_SAMOA", "AS");
	define("AUSTRALIA", "AU");
	define("FEDERATED_STATES_OF_MICRONESIA", "FM");
	define("FIJI", "FJ");
	define("FRENCH_POLYNESIA", "PF");
	define("GUAM", "GU");
	define("KIRIBATI", "KI");
	define("MARSHALL_ISLANDS", "MH");
	define("NAURU", "NR");
	define("NEW_CALEDONIA", "NC");
	define("NEW_ZEALAND", "NZ");
	define("NORTHERN_MARIANA_ISLANDS", "MP");
	define("PALAU", "PW");
	define("PAPUA_NEW_GUINEA", "PG");
	define("PITCAIRN", "PN");
	define("SOLOMON_ISLANDS", "SB");
	define("TONGA", "TO");
	define("TUVALU", "TV");
	define("VANUATU", "VU");

    // Caribbean
	define("ANGUILLA", "AI");
	define("ANTIGUA_AND_BARBUDA", "AG");
	define("ARUBA", "AW");
	define("BAHAMAS", "BS");
	define("BARBADOS", "BB");
	define("BERMUDA", "BM");
	define("CAYMAN_ISLANDS", "KY");
	define("DOMINICA", "DM");
	define("DOMINICAN_REPUBLIC", "DO");
	define("GRENADA", "GD");
	define("GUADELOUPE", "GP");
	define("HAITI", "HT");
	define("JAMAICA", "JM");
	define("MARTINIQUE", "MQ");
	define("NETHERLANDS_ANTILLES", "AN");
	define("PUERTO_RICO", "PR");
	define("ST_KITTS_AND_NEVIS", "KN");
	define("ST_LUCIA", "LC");
	define("ST_VINCENT_AND_THE_GRENADINES", "VC");
	define("TRINIDAD_AND_TOBAGO", "TT");
	define("TURKS_AND_CAICOS_ISLANDS", "TC");
	define("VIRGIN_ISLANDS_BRITISH", "VG");
	define("VIRGIN_ISLANDS_USA", "VI");

	// Central America
	define("BELIZE", "BZ");
	define("COSTA_RICA", "CR");
	define("EL_SALVADOR", "SV");
	define("GUATEMALA", "GT");
	define("HONDURAS", "HN");
	define("NICARAGUA", "NI");
	define("PANAMA", "PA");

	// Europe
	define("ALBANIA", "AL");
	define("ANDORRA", "AD");
	define("ARMENIA", "AM");
	define("AUSTRIA", "AT");
	define("AZERBAIJAN", "AZ");
	define("BELARUS", "BY");
	define("BELGIUM", "BE");
	define("BULGARIA", "BG");
	define("CROATIA", "HR");
	define("CYPRUS", "CY");
	define("CZECH_REPUBLIC", "CZ");
	define("DENMARK", "DK");
	define("ESTONIA", "EE");
	define("FAROE_ISLANDS", "FO");
	define("FINLAND", "FI");
	define("FRANCE", "FR");
	define("GEORGIA", "GE");
	define("GERMANY", "DE");
	define("GIBRALTAR", "BI");
	define("GREECE", "GR");
	define("GREENLAND", "GL");
	define("HUNGARY", "HU");
	define("ICELAND", "IS");
	define("IRELAND", "IE");
	define("ITALY", "IT");
	define("LATVIA", "LV");
	define("LIECHTENSTEIN", "LI");
	define("LITHUANIA", "LT");
	define("LUXEMBOURG", "LU");
	define("MALTA", "MT");
	define("METROPOLITAN_FRANCE", "FX");
	define("MOLDOVA", "MD");
	define("NETHERLANDS", "NL");
	define("NORWAY", "NO");
	define("POLAND", "PL");
	define("PORTUGAL", "PT");
	define("ROMANIA", "RO");
	define("SLOVAKIA", "DK");
	define("SLOVENIA", "SI");
	define("SPAIN", "ES");
	define("SVALBARD_AND_JAN_MAYEN_ISLANDS", "SJ");
	define("SWEDEN", "SE");
	define("SWITZERLAND", "CH");
	define("REPUBLIC_OF_MACEDONIA", "MK");
	define("TURKEY", "TR");
	define("UKRAINE", "UA");
	define("UNITED_KINGDOM", "GB");
	define("VATICAN_CITY", "VA");
	define("YUGOSLAVIA", "YU");

	// Middle East
	define("ISRAEL", "IL");
	define("JORDAN", "JO");
	define("KUWAIT", "KW");
	define("LEBANON", "LB");
	define("OMAN", "OM");
	define("QATAR", "QA");
	define("SAUDI_ARABIA", "SA");
	define("SYRIA", "SY");
	define("UNITED_ARAB_EMIRATES", "AE");
	define("YEMEN", "YE");

	// North America
	define("CANADA", "CA");
	define("MEXICO", "MX");
	define("UNITED_STATES", "US");

	// South America
	define("ARGENTINA", "AR");
	define("BOLIVIA", "BO");
	define("BRAZIL", "BR");
	define("CHILE", "CL");
	define("COLOMBIA", "CO");
	define("EQUADOR", "EC");
	define("ECUADOR", "EC");
	define("FALKLAND_ISLANDS", "FK");
	define("FRENCH_GUIANA", "GF");
	define("GUYANA", "GY");
	define("PARAGUAY", "PY");
	define("PERU", "PE");
	define("SURINAME", "SR");
	define("URUGUAY", "UY");
	define("VENEZUELA", "VE");

	// Others
	define("BAHRAIN", "BH");
	define("BOUVET_ISLANDS", "BV");
	define("BRITISH_INDIAN_OCEAN_TERRITORY", "IO");
	define("CHRISTMAS_ISLANDS", "CX");
	define("COCOS_KEELING_ISLANDS", "CC");
	define("COOK_ISLAND", "CK");
	define("EAST_TIMOR", "TP");
	define("FRENCH_SOUTHERN_TERRITORIES", "TF");
	define("HEARD_AND_MCDONALD_ISLANDS", "HM");
	define("MAURITIUS", "MU");
	define("MONACO", "MC");
	define("MONTSERRAT", "MS");
	define("MYANMAR", "MM");
	define("NIUE", "NU");
	define("NORFOLK_ISLAND", "NF");
	define("SAMOA", "WS");
	define("SAN_MARINO", "SM");
	define("ST_PIERRE_AND_MIQUELON", "PM");
	define("TOKELAU", "TK");
	define("UNITED_STATES_MINOR_OUTLYING_ISLANDS", "UM");
	define("WALLIS_AND_FUTUNA_ISLANDS", "WF");

	define("ANGOLA", "AO");
	define("BOSNIA_AND_HERZEGOWINA", "BA");
	define("CUBA", "CU");
	define("ISLAMIC_REPUBLIC_OF_IRAN", "IR");
	define("IRAQ", "IQ");
	define("DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA", "KP");
	define("LIBYAN_ARAB_JAMAHIRIYA", "LY");
	define("RWANDA", "RW");
	define("SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS", "GS");
	define("DEMOCRATIC_REPUBLIC_OF_THE_CONGO", "CD");
?>